[target.thumbv7m-none-eabi]


runner = "probe-rs run --chip STM32F103C8"


rustflags = [

  # "-C", "linker=arm-none-eabi-gcc",
  # "-C",
  # "link-arg=-Wl,-Tlink.x",
  # "-C", "link-arg=-nostartfiles",
]
[env]

[build]
target = "thumbv7m-none-eabi"
